language: cpp
env:
  - CONAN_SYSREQUIRES_MODE=enabled

cache:
  directories:
  - $HOME/.conan

matrix:
  include:

    - os: linux
      compiler: clang
      addons:
        update: true
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - python3-pip
            - python3-setuptools
      
    - os: osx
      osx_image: xcode12.2
      compiler: clang


addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools

install:
  - pip3 install conan
  - conan user
  - python3 setup.py

script:
  - cmake . -DSPATIAL_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -- -j2
  - ctest .