os: 
  - linux
language: cpp
env:
  - CONAN_SYSREQUIRES_MODE=enabled

addons:
  apt:
    update: true
    packages:
      - python3-pip
      - python3-setuptools

install:
  - pip3 install conan
  - conan user
  - python3 setup.py

script:
  - cmake . -DSPATIAL_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release -- -j2
  - ctest .