# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >-
  Spatial is a cross-platform C++ game engine created on top off google's filament rendering engine.
  This projects uses C++17 and modern cmake features.
baseurl: "/Spatial.Engine" # the subpath of your site, e.g. /blog
url: "https://luizgabriel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  luizgabriel

# Build settings
theme: just-the-docs
plugins:
  - jekyll-seo-tag

back_to_top: true
back_to_top_text: "Back to top"

logo: "/assets/logo.png"

aux_links:
  "GitHub":
    - "https://github.com/luizgabriel/Spatial.Engine"

aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/luizgabriel/Spatial.Engine"

color_theme: auto

collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

