name: build

on:
  push:
    branches:
      - master
      - feature/*
      - release/*
    tags:
      - 'v*'

env:
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    name: Build MacOS
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ">= 3.5"

      - name: Setup
        run: |
          python -m pip install --upgrade pip conan
          python3 $GITHUB_WORKSPACE/setup.py
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Cache Conan Data
        uses: actions/cache@v2
        with:
          path: ~/.conan/
          key: ${{ runner.os }}-${{ hashFiles('conanfile.py') }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        env:
          CC: ${{matrix.config.cc}}
          CXX: ${{matrix.config.cxx}}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DSPATIAL_BUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=../install

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target Spatial.Editor

      - name: Install
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.artifact }}
          path: ${{runner.workspace}}/install/*

  release:
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2

      - name: Upload to Release
        uses: meeDamian/github-release@2.0
        with:
          files: >
            macOS.tar.xz
          gzip: folders
          token: ${{ secrets.GITHUB_TOKEN }}